# https://taskfile.dev

# Setup guide:
# STEP 1: install task, `go get -tool github.com/go-task/task/v3/cmd/task@latest`
# STEP 2: use task to run the "setup" command `go tool task setup`

# Setup tailwind without npm: https://tailwindcss.com/blog/standalone-cli

version: "3"

interval: 500ms # note: this is the watch interval, taskfile will watch for changes every 500ms

vars:
  PORT: 8080
  PROXY_PORT: 7331
  TAILWIND_INPUT_CSS_PATH: ./web/static/assets/styles/input.css
  TAILWIND_OUTPUT_CSS_PATH: ./web/static/assets/css/output.css

tasks:
  setup-tailwind-cli-mac:
    platforms: [darwin]
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
      - chmod +x tailwindcss-macos-arm64
      - mv tailwindcss-macos-arm64 tailwindcss

  setup-tailwind-cli-linux:
    platforms: [linux]
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.18/tailwindcss-linux-x64
      - chmod +x tailwindcss-linux-x64
      - mv tailwindcss-linux-x64 tailwindcss

  setup-tailwind:
    deps:
      - task: setup-tailwind-cli-mac
      - task: setup-tailwind-cli-linux

  setup:
    deps:
      - task: setup-tailwind
      - go get -tool github.com/a-h/templ/cmd/templ@latest

  kill:
    method: none
    desc: Kills process on port 8080
    cmds:
      # kills process on port 8080 on linux
      - cmd: fuser -k {{.PORT}}/tcp > /dev/null 2>&1 || true
        platforms: [linux]

      # kills process on port 8080 on macOS (darwin)
      - cmd: (lsof -nti :{{.PORT}} | xargs kill -9) || true
        platforms: [darwin]

  build:
    desc: build the go binary
    sources:
      - "**/*.go"
      - "./web/static/**/*"
      - "**/*.templ"
      # TODO: uncomment this when we figure how to wait for the entire "templ generate" process
      # - exclude: "**/*_templ.go"
      - exclude: "./dist/**/*"
    generates:
      - "**/*_templ.go"
      - ./dist/main
    cmds:
      - go tool templ generate -lazy .
      - ./tailwindcss --input {{.TAILWIND_INPUT_CSS_PATH}} --output {{.TAILWIND_OUTPUT_CSS_PATH}} --minify
      - go mod tidy
      - go build -o ./dist/main ./main.go

  start-tailwind-watch:
    cmds:
      - ./tailwindcss --input {{.TAILWIND_INPUT_CSS_PATH}} --output {{.TAILWIND_OUTPUT_CSS_PATH}} --minify --watch

  start-templ-watch:
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:{{.PORT}}" --open-browser=false --cmd="go run -tags=debug ."

  start-server:
    cmds:
      - go run -tags=debug .

  # TODO: investigate further (dev only issue)
  # potential race condition here since the watchers in deps are running in parallel
  # find a way to make the dev hot reloading work sequentially
  start:
    method: none
    desc: watch for changes and start the project
    deps: [start-tailwind-watch, start-templ-watch]

  start-prod:
    method: none
    desc: build and start the project for production
    cmds:
      - task: build
      - ./dist/main

  default:
    - task: start
