# https://taskfile.dev

# Setup guide:
# STEP 1: install task, `go get -tool github.com/go-task/task/v3/cmd/task@latest`
# STEP 2: use task to run the "setup" command `go tool task setup`

version: "3"

interval: 500ms # note: this is the watch interval, taskfile will watch for changes every 500ms

tasks:
  setup:
    - go get -tool github.com/a-h/templ/cmd/templ@latest

  kill:
    method: none
    cmds:
      - fuser -k 8080/tcp > /dev/null 2>&1 || true

  templ:
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"
    cmds:
      - go tool templ generate .

  build:
    # method: none
    desc: build the go binary
    deps:
      - kill
      - templ
    sources:
      - "**/*.go"
      - ./web/static/**/*
      - exclude: "**/*_templ.go"
    generates:
      - ./dist/main
    cmds:
      - go mod tidy
      - go build -o ./dist/main ./main.go

  start:
    # method: none
    desc: Builds and starts the golang app
    deps:
      - build
    cmds:
      - "./dist/main"

  default:
    cmds:
      - task: start
