# https://taskfile.dev

# Setup guide:
# STEP 1: install task, `go get -tool github.com/go-task/task/v3/cmd/task@latest`
# STEP 2: use task to run the "setup" command `go tool task setup`

version: '3'

interval: 250ms

tasks:
  setup:
    - go get -tool github.com/a-h/templ/cmd/templ@latest

  build:
    method: none
    desc: build the go binary
    deps:
      - kill
      # - templ # TODO: fix issue where this causes the task -w start not working
    sources:
      - "**/*.go"
      - ./web/static/**/*
    generates:
      - ./dist/main
    cmds:
      - go mod tidy
      - go build -o ./dist/main ./main.go

  start:
    desc: Builds and starts the golang app with live reload
    # watch: true
    cmds:
      - task: build
      - './dist/main'
    sources: 
      - ./**/*.go
      - ./**/*.html

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    sources:
      - "**/*.templ"
    generates:
      - "**/*_temple.go"
    cmds:
      - go tool templ generate .

  templ:watch:
    env:
      TEMPL_EXPERIMENT: rawgo
    sources:
      - "**/*.templ"
    generates:
      - "**/*_temple.go"
    cmds:
      - go tool templ generate --watch

  kill:
    method: none
    cmds:
      - fuser -k 8080/tcp > /dev/null 2>&1 || true

  default:
    cmds:
      - task: start