// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>tenant-manager</title><!-- note: this meta tag is for auto refreshing every 1sec. remove this on production\n    or we find a better way to hot reload --><meta http-equiv=\"Refresh\" content=\"1\"><style>\n    @import \"https://unpkg.com/open-props\";\n    @import \"https://unpkg.com/open-props/normalize.min.css\";\n\n    :root {\n      --card-width: var(--size-content-2);\n      --house-background-grey-color: var(--gray-6);\n      --house-background-green-color: var(--green-6);\n      --house-background-red-color: var(--red-6);\n    }\n\n    main {\n      display: flex;\n      flex-flow: row wrap;\n      align-items: flex-start;\n      gap: var(--size-2);\n      padding: var(--size-2);\n      border: 0.5rem solid var(--gray-7);\n    }\n\n    .card {\n      flex-basis: var(--card-width);\n      display: flex;\n      flex-direction: column;\n      gap: var(--size-2);\n      background: var(--surface-3);\n      border: 1px solid var(--surface-1);\n      padding: var(--size-4);\n      border-radius: var(--radius-3);\n      box-shadow: var(--shadow-2);\n    }\n\n    .house-background {\n      border-radius: var(--radius-3);\n      padding: var(--size-2);\n    }\n\n    .house-background.unpaid {\n      background: var(--house-background-grey-color);\n    }\n\n    .house-background.paid {\n      background: var(--house-background-green-color);\n    }\n\n    .house-background.late {\n      background: var(--house-background-red-color);\n    }\n  </style></head><body><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
