// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Se7enSe7enSe7en/tenant-manager/internal/constants"
import "github.com/Se7enSe7enSe7en/tenant-manager/internal/web/component/tenantcard"
import "github.com/Se7enSe7enSe7en/tenant-manager/internal/web/component/statcard"

func MainPage(tenantList []tenantcard.TenantCardProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page p-4 max-w-7xl mx-auto\"><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-col-4 xl:grid-cols-4 gap-4 mb-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = statcard.StatCard(statcard.StatCardProps{
				Title:    "Total tenants",
				Value:    "4",
				Subtitle: new("Active units"),
				Icon:     new("assets/tenants-icon.svg"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = statcard.StatCard(statcard.StatCardProps{
				Title:    "Paid",
				Value:    "1",
				Subtitle: new("₱15,000 collected"),
				Icon:     new("assets/paid-icon.svg"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = statcard.StatCard(statcard.StatCardProps{
				Title:    "Unpaid",
				Value:    "2",
				Subtitle: new("Awaiting payment"),
				Icon:     new("assets/unpaid-icon.svg"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = statcard.StatCard(statcard.StatCardProps{
				Title:    "Late",
				Value:    "1",
				Subtitle: new("Overdue payments"),
				Icon:     new("assets/late-icon.svg"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><p class=\"text-2xl my-3\">Tenants</p><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-col-3 xl:grid-cols-3 gap-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, tenant := range tenantList {
				templ_7745c5c3_Err = tenantcard.TenantCard(tenant).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = tenantcard.TenantCard(tenantcard.TenantCardProps{
				Name:            "Chim Chay",
				Unit:            "Apt #1",
				Status:          constants.PAID,
				RentAmount:      "₱19,000",
				LastPaymentDate: "2026-01-10",
				Email:           new("email@email.com"),
				PhoneNumber:     new("(+63)98 765 4321"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = tenantcard.TenantCard(tenantcard.TenantCardProps{
				Name:            "Dum Dith",
				Unit:            "Apt #2",
				Status:          constants.LATE,
				RentAmount:      "₱19,000",
				LastPaymentDate: "2026-01-10",
				Email:           new("email@email.com"),
				PhoneNumber:     new("(+63)98 765 4321"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = tenantcard.TenantCard(tenantcard.TenantCardProps{
				Name:            "Dud Li",
				Unit:            "Apt #3",
				Status:          constants.UNPAID,
				RentAmount:      "₱19,000",
				LastPaymentDate: "2026-01-10",
				Email:           new("email@email.com"),
				PhoneNumber:     new("(+63)98 765 4321"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = tenantcard.TenantCard(tenantcard.TenantCardProps{
				Name:            "Dudz And Guy Inc.",
				Unit:            "Apt #4",
				Status:          constants.UNPAID,
				RentAmount:      "₱19,000",
				LastPaymentDate: "2026-01-10",
				Email:           new("email@email.com"),
				PhoneNumber:     new("(+63)98 765 4321"),
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
